[package]
name = "aranet2sonnerie"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
aranet4 = { path = "../aranet4-rs" }
chrono = { version = "0.4.38", features = ["now"] }
clap = "4.5.45"
sonnerie = "0.9.1"
tokio = { version = "1.38.0", features = ["full"] }
